#!/bin/bash
BASEDIR=`dirname $0`

rm ~/.bashrc
ln -s $BASEDIR'/.bashrc' ~/.bashrc

ln -s $BASEDIR'/.vimrc' ~/.vimrc
ln -s $BASEDIR'/.vim' ~/.vim
rm -f $BASEDIR'/.vim/.vim'

ln -s $BASEDIR'/.gitconfig' ~/.gitconfig
ln -s $BASEDIR'/.irbrc' ~/.irbrc
