#!/bin/bash
BASEDIR=`dirname $0`

rm ~/.bashrc
ln -s $BASEDIR'/.bashrc' ~/.bashrc

rm ~/.bash_profile
ln -s $BASEDIR'/.bash_profile' ~/.bash_profile

rm ~/.vimrc
ln -s $BASEDIR'/.vimrc' ~/.vimrc

rm ~/.vim
ln -s $BASEDIR'/.vim' ~/.vim
rm -f $BASEDIR'/.vim/.vim'

rm ~/.gitconfig
ln -s $BASEDIR'/.gitconfig' ~/.gitconfig

rm ~/.irbrc
ln -s $BASEDIR'/.irbrc' ~/.irbrc

rm ~/.gemrc
ln -s $BASEDIR'/.gemrc' ~/.gemrc

rm ~/.ctags
ln -s $BASEDIR'/.ctags' ~/.ctags

rm ~/.tmux.conf
ln -s $BASEDIR'/.tmux.conf' ~/.tmux.conf

mkdir $BASEDIR'/.vim/undodir'
