#!/usr/bin/env ruby

git_bundles = [ 
    "git://github.com/tpope/vim-surround.git",
    "git://github.com/tpope/vim-rails.git",
    "git://github.com/scrooloose/nerdtree.git",
    "git://git.wincent.com/command-t.git; rake make",
    "git://github.com/msanders/snipmate.vim.git",
    "git://github.com/mileszs/ack.vim.git",
    "git://github.com/ghewgill/vim-scmdiff.git",
    "git://github.com/vim-scripts/camelcasemotion.git",
    "git://github.com/vim-scripts/Obvious-Mode.git",
    "git://github.com/vim-scripts/taglist.vim.git",
    "git://github.com/ervandew/supertab.git",
    "git://github.com/vim-scripts/Conque-Shell.git",
    "git://github.com/tpope/vim-repeat.git",
    "git://github.com/vim-ruby/vim-ruby.git",
    "git://github.com/vim-scripts/tComment.git",
    "git://github.com/vim-scripts/local_vimrc.vim.git",
    "git://github.com/vim-scripts/AutoClose.git",
    "git://github.com/tpope/vim-ragtag.git",
    "git://github.com/vim-scripts/minibufexpl.vim.git",
    "git://github.com/vim-scripts/bufexplorer.zip.git"
]

vim_org_scripts = [
    ["javascript", "10728", "syntax"],
#  ["IndexedSearch", "7062",  "plugin"],
#  ["gist",          "12732", "plugin"],
#  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

ROOT_DIR = File.dirname(__FILE__)

bundles_dir = File.join(ROOT_DIR, "bundle")
old_bundles_dir = File.join(ROOT_DIR, "bundle.old.#{ Time.new.to_i }")

FileUtils.mv bundles_dir, old_bundles_dir

FileUtils.mkdir bundles_dir
FileUtils.cd ROOT_DIR

git_bundles.each do |url|
  if url.include? ';'
      after = url.split(';').last.strip
      url = url.split(';').first
  end

  dir = File.join(bundles_dir, url.split('/').last.sub(/\.git$/, ''))

  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  
  `cd #{dir}; #{after}` if after

  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(bundles_dir, name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
